
name: gatk-joint-genotyping

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - nextflow=20.01.0
  - gatk4=4.1.0.0
  - r-gsalib=2.1
  - r-gplots=3.0.1.1
  - r-ggplot2=3.1.0
  - multiqc=1.9
  - snpeff=4.3.1t
  - tabix=0.2.6
