
name: gatk-joint-genotyping

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - nextflow=20.01
  - gatk4=4.1
  - r-gsalib=2.1
  - r-gplots=3.0
  - r-ggplot2=3.1
  - multiqc=1.9
  - snpeff=4.3
  - tabix=0.2
